import { Metadata } from "next";
import AllDoctors from "./all-doctors-data";

export const metadata: Metadata = {
  title: "Our Doctors Team",
  description: "Generated by create next app",
};

export default async function Page() {
  const res = await fetch("http://localhost:3000/jsonfiles/services.json", {
    cache: "no-store", // always get fresh data
  });

  if (!res.ok) {
    throw new Error("Failed to fetch doctors");
  }

  const doctors = await res.json(); // ✅ get actual data

  return <AllDoctors doctors={doctors} />; // ✅ pass to component
}
